### PR TITLE
init rmarkdown template

### PR DESCRIPTION
**Pull request by JosephBARBIERDARNAL**
reference issue: #89

### CODE REVIEW

**Comment by JosephBARBIERDARNAL** [comment]
I believe this is ready for review @dgkeyes.

There are a couple of things I'm not entirely satisfied with (though I haven't found a solution):

- The way CSS/logo files are referenced, such as `../../../../assets/omni_rmarkdown.css`. I'm sure there's a more efficient way to handle this, but I haven't been able to figure it out.
- The margins around the `h1`, `h2`, `h3`, and `p` tags. I can't pinpoint the source, and they seem a bit off visually.

<br>

Preview:

Screenshot 2024-11-11 at 14 19 08

**Comment by dgkeyes** [comment]
Thanks @JosephBARBIERDARNAL. This looks great overall.

> The way CSS/logo files are referenced, such as ../../../../assets/omni_rmarkdown.css. I'm sure there's a more efficient way to handle this, but I haven't been able to figure it out.

I'm not sure how to handle this. @tvroylandt any ideas?

> The margins around the h1, h2, h3, and p tags. I can't pinpoint the source, and they seem a bit off visually.

These look ok to me. Is there something in particular that seems off to you?

**Comment by JosephBARBIERDARNAL** [comment]
> These look ok to me. Is there something in particular that seems off to you?

I'm probably used to lower margins, but if you think it's ok, it's ok with me.

**Comment by dgkeyes** [comment]
I'm going to go ahead and merge this. We can make more changes later if desired.

**Pull request merged**
